name: Maven CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package
        working-directory: ./my-app

      - name: Run tests with Maven
        run: mvn test
        working-directory: ./my-app

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-app-jar
          path: my-app/target/my-app-1.0-SNAPSHOT.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download JAR artifact
        uses: actions/download-artifact@v3
        with:
          name: my-app-jar

      - name: List downloaded files
        run: ls -al my-app/target/

      - name: Create temporary directory and copy JAR file
        run: |
          mkdir -p /tmp/my-app
          cp my-app/target/my-app-1.0-SNAPSHOT.jar /tmp/my-app/
          ls -al /tmp/my-app/

      - name: Upload JAR to EC2 using SSM
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          # Copy the JAR file from the GitHub runner to the EC2 instance using SSM
          aws ssm send-command \
            --instance-ids "i-0839a8d070763f097" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploying application" \
            --parameters 'commands=["mkdir -p /opt/my-app","aws s3 cp /tmp/my-app/my-app-1.0-SNAPSHOT.jar /opt/my-app/","sudo systemctl restart my-app"]' \
            --output text
