name: Maven CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package
        working-directory: ./my-app

      - name: Run tests with Maven
        run: mvn test
        working-directory: ./my-app

      - name: Archive JUnit test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: my-app/target/surefire-reports/

      - name: Upload WAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-app-war
          path: my-app/target/hello-world-1.0-SNAPSHOT.war

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download WAR artifact
        uses: actions/download-artifact@v3
        with:
          name: my-app-war

      - name: Deploy to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          chmod 600 /tmp/ssh_key.pem
          echo "$SSH_PRIVATE_KEY" > /tmp/ssh_key.pem
          scp -i /tmp/ssh_key.pem -o StrictHostKeyChecking=no hello-world-1.0-SNAPSHOT.war $USER@$HOST:/home/$USER
          ssh -i /tmp/ssh_key.pem -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
            sudo systemctl stop tomcat
            sudo cp /home/$USER/hello-world-1.0-SNAPSHOT.war /opt/tomcat/webapps/
            sudo systemctl start tomcat
          EOF
