name: Maven CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Maven (debug mode)
        run: mvn clean package -X  # Adding -X for debug mode
        working-directory: ./my-app

      - name: Check target directory after build
        run: ls -al ./my-app/target
        continue-on-error: true  # Continue even if this fails so we can inspect logs

      - name: Run tests with Maven
        run: mvn test
        working-directory: ./my-app

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-app-jar
          path: my-app/target/my-app-1.0-SNAPSHOT.jar
