name: Maven CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package
        working-directory: ./my-app

      - name: Run tests with Maven
        run: mvn test
        working-directory: ./my-app

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-app-jar
          path: my-app/target/my-app-1.0-SNAPSHOT.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download JAR artifact
        uses: actions/download-artifact@v3
        with:
          name: my-app-jar

      - name: Deploy to EC2 via SSM
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          INSTANCE_ID: ${{ secrets.EC2_INSTANCE_ID }}
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=instanceids,Values=$INSTANCE_ID" \
            --parameters 'commands=["aws s3 cp s3://your-bucket/my-app-1.0-SNAPSHOT.jar /home/ec2-user/","sudo systemctl stop my-app","sudo cp /home/ec2-user/my-app-1.0-SNAPSHOT.jar /opt/my-app/","sudo systemctl start my-app"]' \
            --comment "Deploying application"
