name: Maven CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -T 2C
        working-directory: ./my-app

      - name: Run tests with Maven
        run: mvn test
        working-directory: ./my-app

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-app-jar
          path: ./my-app/target/my-app-1.0-SNAPSHOT.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download JAR artifact
        uses: actions/download-artifact@v3
        with:
          name: my-app-jar

      - name: Create temporary directory and copy JAR file
        run: |
          mkdir -p /tmp/my-app
          cp my-app-1.0-SNAPSHOT.jar /tmp/my-app/
          ls -al /tmp/my-app/

      - name: Deploy JAR to EC2 via SSM
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          INSTANCE_ID: i-0839a8d070763f097
        run: |
          # Define the deployment command
          DEPLOY_COMMAND="sudo mkdir -p /opt/my-app && sudo cp /tmp/my-app/my-app-1.0-SNAPSHOT.jar /opt/my-app/ && sudo systemctl restart my-app"
          
          # Escape special characters for JSON formatting
          ESCAPED_COMMAND=$(echo "$DEPLOY_COMMAND" | sed 's/"/\\"/g')

          # Run the deployment command using AWS SSM
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=instanceids,Values=$INSTANCE_ID" \
            --parameters "commands=[\"$ESCAPED_COMMAND\"]" \
            --comment "Deploying Maven application to EC2 instance"
