name: Maven CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package
        working-directory: ./my-app

      - name: Run tests with Maven
        run: mvn test
        working-directory: ./my-app

      - name: Archive JUnit test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: my-app/target/surefire-reports/

      - name: Deploy to EC2
        run: |
          scp -i C:/Users/v/Downloads/shubh1.pem ./my-app/target/hello-world-1.0-SNAPSHOT.war ec2-user@13.201.131.153:/opt/tomcat/webapps
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
